### ISSUE TITLE
Calibrate Odometry: How?

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_robot#19] opened 2013-09-18 09:50 UTC
Is it possible to calibrate the odometry of the robot? We discovered a systemic error in the odometry (the robot is accumulating rotation even if it is not rotating). @gestom and @cdondrup know the details. It would improve mapping and localisation if this systemic error could be avoided.

**Comment by cburbridge** [comment] 2013-09-18 12:45
I have not seen this on Bob, does it happen all the time or just occasionally? At what rate does it change?

**Comment by marc-hanheide** [comment] 2013-09-18 13:30
I don't know the details, @gestom should.

**Comment by gestom** [comment] 2013-09-18 14:43
Hi, 

let me describe our observation during Linda's autonomous runs. By odometry, I mean the numbers reported directly on Linda's status display located close to the main (key) switch.

Let Linda start on the charging station with her odometry reset, i.e. 0,0,0.
After the patrolling run, which basically consists of undocking, going through four waypoints and docking with the station (i.e. reaching the starting position), her odometer reports her heading as something like 12°+-2°. Every consequent patrolling run increases the reported heading approximately by this value. The x,y values behave similarly. Therefore, most of the odometric error is actually systematic and is probably caused by discrepancy of the real and assumed distance of Lindas wheels. 

IMHO, this issue is difficult to correct in ROS simply because error in heading affects the x,y values as well. I assume, that the odometry calculation is actually realized by some microcontroller in Linda's base. The question is if we can adjust the imprecise constant by configuring this microcontroller.

**Comment by Jailander** [comment] 2013-09-19 15:11
Hi, 
To illustrate this a little more, you can see in these images how the "world rotates" every time Linda does a patrolling run is we don't reset the odometry before she starts it.

![2d_30-08-13-11-20](https://f.cloud.github.com/assets/5035967/1173787/7b30468e-213d-11e3-8d9f-9b665ec96115.png)
![2d_30-08-13-11-25](https://f.cloud.github.com/assets/5035967/1173788/7b3e2984-213d-11e3-9aef-f338ecf0f67f.png)
![2d_30-08-13-11-30](https://f.cloud.github.com/assets/5035967/1173789/7b4f33b4-213d-11e3-8846-7b4854a0b263.png)
![2d_30-08-13-11-35](https://f.cloud.github.com/assets/5035967/1173790/7b5376c2-213d-11e3-9378-9e8172494598.png)

**Comment by chmartin21** [comment] 2013-09-24 07:47
The odometry calculation is realized within a FPGA in the robots base. The SCITOS robots don't have an option to calibrate the odometry. As on all mobile robots, a certain amount of such errors are "normal". Your localization software should be able to deal with this errors. Which localization are you using? Can you make the same test on all (affected) robots? Can you also tell us the serial number of the robots?

**Comment by marc-hanheide** [comment] 2013-09-24 07:51
@chmartin21 just to be clear, it's not a big problem and our AMC localisation can well deal with it. Of course errors in odometry are normal and well expected. But as we discovered the error to be _systematic_ we thought there is probably an easy way to minimise the error. 
This is all on Lincoln's robot (don't know the serial number as I'm not in the lab ATM).

**Comment by gestom** [comment] 2013-09-24 08:00
Hi, 
I agree that it's not a major problem for us.
Still, eliminating this systematic error might increase the odometry precision tenfold. Since the odometry is calculated by a FIELD PROGRAMMABLE Gate Array, then it's actually possible to change it, right ?

**Comment by chmartin21** [comment] 2013-09-24 08:01
Actually, all your robots should be equipped with an additional gyroscope, which helps to reduce especially the rotation error. Due to some problems with our suppliers, only the robots in Aachen and Stockholm are equipped with the gyroscope at the moment. We will deliver the gyroscope modules for the other robots as soon as possible. The modules are already here. I assume, that the will send to you within the next week.

**Comment by marc-hanheide** [comment] 2013-09-24 08:14
Ah! That's exciting news indeed! @gestom and @tduckett will love to hear that! Thanks.

**Comment by marc-hanheide** [comment] 2013-09-30 15:58
@chmartin21 I can confirm that at least LEEDS ( @agcohn ) and UOL ( @gestom @tduckett @Jailander @cdondrup ) have received the gyros. However, we don't know what to do with it. Can you provide assembly and setup instructions rather soon, as we have our STRANDS general assembly on Thursday and would like to discuss this there. Thanks!

**Comment by chmartin21** [comment] 2013-09-30 17:18
The assembly of the gyro module is quiet easy. Together with the robot, you should have received a small torx wrench, which fits in the smalls screws at the electronic box. Please do the follwoing: 
1.) Turn off the robot.
2.) Remove one of the aluminum cover plates in the upper part of the electronic box (next to the EBC module) using the torx wrench.
3.) Put the gyro module into the free slot.
4.) Fix the gyro module with the torx wrench.

Thats it. There is no additional configuration necessary. The gyro module will be detected and used automatically by the motor controller unit.

**Comment by gestom** [comment] 2013-09-30 18:46
While I hope that the gyro might suppress the odometry systematic error, it would be really nice to have a possibility for odometry calibration. As far as I understand the FPGA technology, it is still possible to modify the design.

**Comment by cdondrup** [comment] 2013-09-30 18:47
Might be a stupid question, but what is the "Wall Mounting Bracket" and the "Adapter Upper Robot Case" for if you only put the gyro into the electronics case?

**Comment by chmartin21** [comment] 2013-10-01 09:52
@cdondrup : The additional parts have nothing to do with the gyro. As far as I know, for each robot some additional part where ordered. The flexible "Wall Mounting Bracket" can be used as an replacement for the fixed display mount of the robot. Furthermore, there was the requirement for mounting the PTU on top of robot without the head. I assume, that the "Adapter Upper Robot Case" is for that.

**Comment by cdondrup** [comment] 2013-10-07 10:17
@chmartin21 we just installed the gyro but non of the 3 LEDs is responding. I thought that at least the "run" LED should be active if it is running.

**Comment by chmartin21** [comment] 2013-10-07 11:48
Before we shipped the gyro modules, all modules were tested. Please can you open cover of the slot right of the gyro module. Is there any LED visible or blinking on the module? Furthermore, please send us a photo which shows the assembled module in the robot, the serial number of the module and the serial number of you robot.

**Comment by cdondrup** [comment] 2013-10-07 12:52
We checked and there are no LEDs on the module. Just the three on the cover plate for "Run", "Conn", and "Active" and none of them is lit. See images for requested information:
![2013-10-07 13 45 29](https://f.cloud.github.com/assets/4293484/1280310/252fe40e-2f4f-11e3-9f5a-dcf28ee93112.jpg)
![2013-10-07 13 43 24](https://f.cloud.github.com/assets/4293484/1280311/2d6e75f4-2f4f-11e3-8326-7f28cd732a9c.jpg)
![2013-10-07 13 43 44](https://f.cloud.github.com/assets/4293484/1280313/323615c4-2f4f-11e3-92b7-6708eedca278.jpg)
![2013-10-07 13 39 23](https://f.cloud.github.com/assets/4293484/1280317/38ad15c4-2f4f-11e3-8ce8-54339a4d9f70.jpg)
![2013-10-07 13 44 16](https://f.cloud.github.com/assets/4293484/1280318/3a8ae63c-2f4f-11e3-9be1-98dbafcfb88c.jpg)

**Comment by chmartin21** [comment] 2013-10-07 13:00
Strange. Somehow the module seems broken. I assume, that you already have tried another slot and the module is also not working there... Therefore, we have to check the module. Can you send it back to us?

**Comment by cdondrup** [comment] 2013-10-07 13:05
Yes we also tried the slot directly next to the EBC. No change in behaviour.
We will ship it back to you. Is Am Vogelherd 22 the right address?

**Comment by chmartin21** [comment] 2013-10-07 13:06
Our full address is:
    MetraLabs GmbH
    Am Vogelherd 22
    D-98693 Ilmenau
    Germany

**Comment by cdondrup** [comment] 2013-10-07 13:28
Thanks.
It's in the mail and should be with you at the end of the week.

**Comment by cdondrup** [comment] 2013-11-27 13:39
@chmartin21 out new gyro arrived today. We will try it out on the weekend because we can't stop the robot during the marathon. We will keep you in the loop if it works this time.

**Comment by cdondrup** [comment] 2013-12-02 14:07
It seems the gyro is working now. The "Run" and "Conn" LEDs are lit.

**Comment by cburbridge** [comment] 2014-10-06 08:38
I'm going to close this issue as everyone now has the gyro add-on card installed, and systematic odometry error has not been mentioned since so it must be ok. If you fee otherwise, re-open.

**Comment by cdondrup** [comment] 2014-10-06 15:47
Actually we still have a systematic odometry error. It still drifts to the right.

**Comment by marc-hanheide** [comment] 2015-02-21 15:20
still? Will we do anything about it?

**Comment by cdondrup** [comment] 2015-02-22 19:27
@Jailander and @gestom should now if this is still an issue. But since there has been no activity, I guess it is.

**Closed as completed** 2017-01-02 21:48 UTC
Labels: question
